/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as ApiPaymentsRouteImport } from './routes/api/payments'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiPaymentsIdRouteImport } from './routes/api/payments.$id'
import { Route as ApiPaymentsIdCompleteRouteImport } from './routes/api/payments.$id.complete'
import { Route as ApiPaymentsIdFailRouteImport } from './routes/api/payments.$id.fail'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsRoute = ApiPaymentsRouteImport.update({
  id: '/api/payments',
  path: '/api/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsIdRoute = ApiPaymentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPaymentsRoute,
} as any)
const ApiPaymentsIdCompleteRoute = ApiPaymentsIdCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => ApiPaymentsIdRoute,
} as any)
const ApiPaymentsIdFailRoute = ApiPaymentsIdFailRouteImport.update({
  id: '/fail',
  path: '/fail',
  getParentRoute: () => ApiPaymentsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/api/payments': typeof ApiPaymentsRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/payments/$id': typeof ApiPaymentsIdRouteWithChildren
  '/api/payments/$id/complete': typeof ApiPaymentsIdCompleteRoute
  '/api/payments/$id/fail': typeof ApiPaymentsIdFailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/api/payments': typeof ApiPaymentsRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/payments/$id': typeof ApiPaymentsIdRouteWithChildren
  '/api/payments/$id/complete': typeof ApiPaymentsIdCompleteRoute
  '/api/payments/$id/fail': typeof ApiPaymentsIdFailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/api/payments': typeof ApiPaymentsRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/payments/$id': typeof ApiPaymentsIdRouteWithChildren
  '/api/payments/$id/complete': typeof ApiPaymentsIdCompleteRoute
  '/api/payments/$id/fail': typeof ApiPaymentsIdFailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/api/payments'
    | '/api/auth/login'
    | '/api/payments/$id'
    | '/api/payments/$id/complete'
    | '/api/payments/$id/fail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/api/payments'
    | '/api/auth/login'
    | '/api/payments/$id'
    | '/api/payments/$id/complete'
    | '/api/payments/$id/fail'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/api/payments'
    | '/api/auth/login'
    | '/api/payments/$id'
    | '/api/payments/$id/complete'
    | '/api/payments/$id/fail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  ApiPaymentsRoute: typeof ApiPaymentsRouteWithChildren
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments': {
      id: '/api/payments'
      path: '/api/payments'
      fullPath: '/api/payments'
      preLoaderRoute: typeof ApiPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/$id': {
      id: '/api/payments/$id'
      path: '/$id'
      fullPath: '/api/payments/$id'
      preLoaderRoute: typeof ApiPaymentsIdRouteImport
      parentRoute: typeof ApiPaymentsRoute
    }
    '/api/payments/$id/complete': {
      id: '/api/payments/$id/complete'
      path: '/complete'
      fullPath: '/api/payments/$id/complete'
      preLoaderRoute: typeof ApiPaymentsIdCompleteRouteImport
      parentRoute: typeof ApiPaymentsIdRoute
    }
    '/api/payments/$id/fail': {
      id: '/api/payments/$id/fail'
      path: '/fail'
      fullPath: '/api/payments/$id/fail'
      preLoaderRoute: typeof ApiPaymentsIdFailRouteImport
      parentRoute: typeof ApiPaymentsIdRoute
    }
  }
}

interface ApiPaymentsIdRouteChildren {
  ApiPaymentsIdCompleteRoute: typeof ApiPaymentsIdCompleteRoute
  ApiPaymentsIdFailRoute: typeof ApiPaymentsIdFailRoute
}

const ApiPaymentsIdRouteChildren: ApiPaymentsIdRouteChildren = {
  ApiPaymentsIdCompleteRoute: ApiPaymentsIdCompleteRoute,
  ApiPaymentsIdFailRoute: ApiPaymentsIdFailRoute,
}

const ApiPaymentsIdRouteWithChildren = ApiPaymentsIdRoute._addFileChildren(
  ApiPaymentsIdRouteChildren,
)

interface ApiPaymentsRouteChildren {
  ApiPaymentsIdRoute: typeof ApiPaymentsIdRouteWithChildren
}

const ApiPaymentsRouteChildren: ApiPaymentsRouteChildren = {
  ApiPaymentsIdRoute: ApiPaymentsIdRouteWithChildren,
}

const ApiPaymentsRouteWithChildren = ApiPaymentsRoute._addFileChildren(
  ApiPaymentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  ApiPaymentsRoute: ApiPaymentsRouteWithChildren,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
